import test from 'node:test';
import assert from 'node:assert/strict';
import { createApp } from '../server.js';
async function withServer(options, run) { const server=createApp(options).listen(0,'127.0.0.1'); await new Promise(resolve=>server.once('listening',resolve)); const base=`http://127.0.0.1:${server.address().port}`; try { await run(base); } finally { await new Promise(resolve=>server.close(resolve)); } }
const request=(base,body,headers={})=>fetch(base+'/api/generate',{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(body)});
const valid={prompt:'Build a page',language:'HTML / CSS / JS'};
test('starts without a key and blocks server files',()=>withServer({env:{}},async base=>{assert.equal((await (await fetch(base+'/api/health')).json()).aiConfigured,false);for(const file of ['server.js','package.json','.env','README.md']) assert.equal((await fetch(base+'/'+file)).status,404); assert.equal((await request(base,valid)).status,503);assert.equal((await fetch(base+'/')).status,200);}));
test('validates all user inputs and malformed JSON',()=>withServer({env:{}},async base=>{for(const body of [{},{...valid,currentCode:{}},{...valid,language:'bad'},{...valid,mode:'bad'},{...valid,prompt:' '},{...valid,currentCode:'x'.repeat(60001)}])assert.equal((await request(base,body)).status,400);const bad=await fetch(base+'/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:'{'});assert.equal(bad.status,400);assert.ok((await bad.json()).error);}));
test('generation, explanation and rate limit',()=>withServer({env:{},rateLimit:2,client:{responses:{create:async args=>{assert.equal(args.store,false);return {output_text:'hello',status:'completed'};}}}},async base=>{assert.equal((await (await request(base,valid)).json()).code,'hello');assert.equal((await (await request(base,{...valid,mode:'explain'})).json()).explanation,'hello');assert.equal((await request(base,valid)).status,429);}));
test('maps provider failures without leaking secrets',async()=>{for(const [error,status,word]of [[{status:401},503,'key'],[{status:429,code:'insufficient_quota'},429,'balance'],[{status:429,code:'credit_balance_exhausted'},429,'balance'],[{status:404},503,'model'],[{name:'APIConnectionTimeoutError'},504,'long']])await withServer({env:{},client:{responses:{create:async()=>{throw {...error,message:'secret'};}}}},async base=>{const r=await request(base,valid);assert.equal(r.status,status);const data=await r.json();assert.ok(data.error.includes(word));assert.ok(!data.error.includes('secret'));});});
test('rejects truncated and empty responses',async()=>{for(const response of [{status:'incomplete',output_text:'partial'},{status:'completed',output_text:''}])await withServer({env:{},client:{responses:{create:async()=>response}}},async base=>assert.equal((await request(base,valid)).status,502));});
test('access token and origin checks',()=>withServer({env:{APP_ACCESS_TOKEN:'workspace-secret',FRONTEND_ORIGIN:'https://trusted.example'},client:{responses:{create:async()=>({output_text:'ok'})}}},async base=>{assert.equal((await request(base,valid)).status,401);assert.equal((await request(base,valid,{'X-App-Token':'workspace-secret'})).status,200);assert.equal((await request(base,valid,{Origin:'https://evil.example'})).status,403);const trusted=await request(base,valid,{Origin:'https://trusted.example','X-App-Token':'workspace-secret'});assert.equal(trusted.status,200);assert.equal(trusted.headers.get('access-control-allow-origin'),'https://trusted.example');}));

test('HTTPS frontend works behind a TLS-terminating proxy',()=>withServer({env:{},client:{responses:{create:async()=>({output_text:'ok'})}}},async base=>{const origin=base.replace('http:','https:');assert.equal((await request(base,valid,{Origin:origin})).status,200);assert.equal((await request(base,valid,{Origin:'https://other.example'})).status,403);}));
