const $=s=>document.querySelector(s);const prompt=$('#prompt'),language=$('#language'),code=$('#code'),editor=$('#editorWrap'),lines=$('#lines');
const samples={
'HTML / CSS / JS':`<!doctype html>
<html>
<head>
  <meta charset="UTF-8">
  <title>AI CodeX Project</title>
  <style>
    body { font-family: system-ui; margin: 0; min-height: 100vh; display: grid; place-items: center; background: #0b1020; color: white; }
    .card { padding: 40px; border: 1px solid #334155; border-radius: 20px; background: #111827; text-align: center; }
    button { padding: 10px 16px; border: 0; border-radius: 10px; cursor: pointer; }
  </style>
</head>
<body>
  <div class="card">
    <h1>Built with AI CodeX</h1>
    <p>Your idea is ready to become code.</p>
    <button onclick="alert('Hello!')">Run action</button>
  </div>
</body>
</html>`,
Python:`def build_with_ai_codex(idea: str) -> dict:
    """Starter generated by AI CodeX."""
    return {
        "idea": idea,
        "status": "ready",
        "message": f"Building: {idea}"
    }

if __name__ == "__main__":
    print(build_with_ai_codex("My next project"))`,
JavaScript:`const buildProject = (idea) => ({
  idea,
  status: "ready",
  createdAt: new Date().toISOString()
});

console.log(buildProject("My next project"));`,
TypeScript:`type Project = { idea: string; status: "ready" };

function buildProject(idea: string): Project {
  return { idea, status: "ready" };
}

console.log(buildProject("My next project"));`,
React:`export default function App() {
  return (
    <main>
      <h1>Built with AI CodeX</h1>
      <p>Describe, generate, improve, ship.</p>
    </main>
  );
}`,
Java:`public class Main {
  public static void main(String[] args) {
    System.out.println("Built with AI CodeX");
  }
}`,
'C++':`#include <iostream>
int main() {
  std::cout << "Built with AI CodeX" << std::endl;
  return 0;
}`,
SQL:`CREATE TABLE projects (
  id INTEGER PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  language VARCHAR(40),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);`};
function renderLines(){const n=code.value.split('\n').length;lines.innerHTML=Array.from({length:n},(_,i)=>i+1).join('<br>')}
function generate(){const lang=language.value;code.value=samples[lang]||samples.JavaScript;editor.classList.add('show');$('#langStatus').textContent=lang;renderLines();if(lang==='HTML / CSS / JS') preview()}
function preview(){if(language.value!=='HTML / CSS / JS'){alert('Live Preview is available for HTML / CSS / JS projects.');return}$('#preview').classList.add('show');$('#frame').srcdoc=code.value}
$('#generate').onclick=generate;$('#previewBtn').onclick=preview;$('#closePreview').onclick=()=>$('#preview').classList.remove('show');code.addEventListener('input',renderLines);
$('#copyBtn').onclick=async()=>{await navigator.clipboard.writeText(code.value);$('#copyBtn').textContent='Copied!';setTimeout(()=>$('#copyBtn').textContent='Copy',1200)};
document.querySelectorAll('.suggestions button').forEach(b=>b.onclick=()=>{prompt.value=b.dataset.prompt;prompt.focus()});
$('#newChat').onclick=()=>{editor.classList.remove('show');prompt.value='';code.value='';$('#preview').classList.remove('show')};
$('#themeBtn').onclick=()=>document.body.classList.toggle('light');
prompt.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter')generate()});